name = "mpd-to-m3u8-converter"
main = "src/index.ts"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

[vars]
# Add any environment variables here

[[routes]]
pattern = "your-domain.com/*"
zone_name = "your-domain.com"
